os: linux
dist: focal

addons:
  apt_packages:
    - p7zip-full
    - rsync

language: php
php:
  - '7.4'

script:
  - bash CI/validator.sh

notifications:
  recipients:
    - kyle@kxnrl.com
    - 1149873216@qq.com
    - 834888744@qq.com
    - 286921966@qq.com
    - 378379682@qq.com
  on_success: never
  on_failure: always
